name: Sample trigger pipeline

on:
  workflow_dispatch:

jobs:
  test-job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Print Hello
        run: echo "hello world!"
  test-job1:
    runs-on: ubuntu-latest
    needs: test-job
    steps:
      - name: Print welcome message
        run: echo "hello world! welcome to git hub worlflow for begginers"
  test-job2:
    runs-on: ubuntu-latest
    needs: test-job1
    steps:
      - name: Print some messagesfor testing
        run: echo "this is chain wokflow files testing"
